.TH 0ALIAS 1 "2009" "Thomas Leonard" ""
.SH NAME
0alias \- create quick scripts to run 0launch

.SH SYNOPSIS

.B 0alias
\fBALIAS\fP [\fBINTERFACE\fP [\fBCOMMAND\fP]]

.SH DESCRIPTION
.PP
Having to keep typing the full URI for a program each time you want to run it
with 0launch is annoying. 0alias will create a little script in your PATH to
do it for you.

.SH EXAMPLES

.PP
A program can be invoked using 0launch:

.B 0launch http://rox.sourceforge.net/2005/interfaces/Edit

.PP
To avoid having to keep entering the URI, create an alias:

.B 0alias rox-edit http://rox.sourceforge.net/2005/interfaces/Edit

.PP
To run Edit now:

.B rox-edit

.PP
To select a different version, or check for updates:

.B 0alias rox-edit

.PP
If an interface provides more than one program, you can specify which
one to use instead of the default. e.g.

.B 0alias svn http://example.com/subversion

.B 0alias svnadmin http://example.com/subversion svnadmin


.SH COMMAND-LINE OPTIONS

.TP
\fB-d=DIR\fP, \fB--dir=DIR\fP
Install the script into directory DIR, rather than searching for a suitable
directory in $PATH.

.TP
\fB-h\fP, \fB--help\fP
Show the built-in help text.

.TP
\fB-m\fP, \fB--manpage\fP
Display the manpage for the alias script given as the single argument. The
alias can be an absolute pathname, or the name of a script in $PATH. If the
argument isn't an alias script, or if multiple arguments are given, then all
arguments are passed to the system 'man' command. This allows you to alias your
man command like this:

alias man='0alias --manpage'

.TP
\fB-r\fP, \fB--resolve\fP
Print the interface URI for the given alias script to stdout.

.TP
\fB-V\fP, \fB--version\fP
Display version information.

.SH LICENSE
.PP
Copyright (C) 2007 Thomas Leonard.

.PP
You may redistribute copies of this program under the terms of the GNU Lesser General Public License.
.SH BUGS
.PP
Please report bugs to the developer mailing list:

http://0install.net/support.html

.SH AUTHOR
.PP
The Zero Install Injector was created by Thomas Leonard.

.SH SEE ALSO
0launch(1), 0desktop(1)
.PP
The Zero Install web-site:

.B http://0install.net
