.TH 0ALIAS 1 "2012" "Thomas Leonard" ""
.SH NAME
0alias \(em create quick scripts to run 0launch

.SH SYNOPSIS

.B 0alias
\fBALIAS\fP [\fBINTERFACE\fP [\fBMAIN\fP]]

.SH DESCRIPTION
.PP
0alias is deprecated. Use `0install add' instead.

.SH LICENSE
.PP
Copyright (C) 2012 Thomas Leonard.

.PP
You may redistribute copies of this program under the terms of the GNU Lesser General Public License.
.SH BUGS
.PP
Please report bugs to the developer mailing list:

http://0install.net/support.html

.SH AUTHOR
.PP
The Zero Install Injector was created by Thomas Leonard.

.SH SEE ALSO
0install(1), 0launch(1), 0desktop(1)
.PP
The Zero Install web-site:

.B http://0install.net
