#!/usr/bin/env python

import locale
from logging import warn
try:
	locale.setlocale(locale.LC_ALL, '')
except locale.Error:
	warn('Error setting locale (eg. Invalid locale)')

import os, sys; sys.path.append(os.path.expanduser('~/lib/python'))

from zeroinstall.gtkui import desktop
desktop.main(sys.argv[1:])
