#!/usr/bin/env python
import sys
import locale
from logging import warn
try:
	locale.setlocale(locale.LC_ALL, '')
except locale.Error:
	warn('Error setting locale (eg. Invalid locale)')

## PATH ##

from zeroinstall.cmd import main
import sys
main(sys.argv[1:])
