#!/usr/bin/env python
import sys
import locale
from logging import warn
try:
	locale.setlocale(locale.LC_ALL, '')
except locale.Error:
	warn('Error setting locale (eg. Invalid locale)')

## PATH ##

import sys

# Hack to let the OCaml front-end chain the Python.
# Using "python -m" isn't safe, because it adds the current directory
# to PYTHONPATH.

if sys.argv[1] == 'store':
	from zeroinstall.cmd.store import main
	main(sys.argv[2:])
else:
	from zeroinstall.cmd import main
	main(sys.argv[1:])
