.TH 0LAUNCH 1 "2011" "Thomas Leonard" ""
.SH NAME
0launch \(em download and run programs by URL

.SH SYNOPSIS

.B 0launch
[\fBOPTION\fP]... \fBPROGRAM\fP [\fBARG\fP]...

.SH DESCRIPTION
.PP
0launch runs the given program. PROGRAM is either a URL in the form
`http://site/program.xml' or a local path name like `/path/to/program.xml'.

.PP
If the program is not already on your computer, 0launch downloads information about
which versions are available, and lets you choose one to download. It will also
(automatically) do the same for any libraries the program needs.

.PP
Note that much of the functionality that was originally in 0launch has now moved to
0install(1).

.B 0launch PROGRAM ARGS

.PP
is roughly equivalent to

.B 0install run PROGRAM ARGS

See the 0install(1) man-page for more information.

.SH EXAMPLES

.PP
When a program is available using 0launch, it will have an associated URL. To
run the program, simply invoke 0launch with this as an argument:

.B 0launch http://rox.sourceforge.net/2005/interfaces/Edit

.PP
The first time you do this, details about the program are downloaded and
cached, and you will be prompted to confirm the versions to use. In future,
the program will run directly from the cache without confirmation.

.PP
To check for new versions:

.B 0launch \-\-refresh http://rox.sourceforge.net/2005/interfaces/Edit

.PP
To avoid having to keep typing the full URI, use the 0alias(1) command
to create shortcuts to run your programs.

.SH COMMAND-LINE OPTIONS

.TP
0launch takes many of the same options as "0install run". This page just lists the differences:

.TP
\fB\-d\fP, \fB\-\-download\-only\fP
Deprecated. Use "0install download" instead.

.TP
\fB\-f\fP, \fB\-\-feed\fP
Deprecated. Use "0install add-feed" or "0install remove-feed" instead.

.TP
\fB\-\-get\-selections\fP
Deprecated. Use "0install select" instead.

.TP
\fB\-i\fP, \fB\-\-import\fP
Deprecated. Use "0install import" instead.

.TP
\fB\-l\fP, \fB\-\-list\fP
Deprecated. Use "0install list" instead.

.TP
\fB\-\-select\-only\fP
Deprecated. Use "0install select" instead.

.TP
\fB\-\-set\-selections=FILE\fP
Deprecated. Just give FILE as the PROGRAM.

.TP
\fB\-\-show\fP
Deprecated. Use "0install select" instead.

.SH DEBUGGING TIPS

.PP
To debug 0launch itself, use the \-\-verbose and \-\-console options. For example:

.B $ 0launch \-vvc http://myprog

.PP
To trace or debug programs run by 0launch, use the \-\-wrapper option.
For example, to run \fBmyprog \-\-help\fP, displaying all calls to open(2):

.B $ 0launch \-\-wrapper="strace \-e open" http://myprog \-\-help

If your program is interpreted (e.g. a Python program), and you wish to debug
the interpreter running it, you can do it like this:

.B $ 0launch \-\-wrapper="gdb \-\-args python" http://myprog \-\-help

.SH FILES

Configuration files (see freedesktop.org basedir spec):

.IP "~/.config/0install.net/injector/global"
Global configuration settings.

.IP "~/.config/0install.net/injector/trustdb.xml"
List of trusted keys.

.IP "~/.config/0install.net/injector/interfaces"
Per-interface settings, and extra feeds.

.PP
Cached data (can be re-downloaded if lost):

.IP "~/.cache/0install.net/interfaces"
Downloaded cached feed files.

.IP "~/.cache/0install.net/implementations"
Downloaded cached implementations, indexed by manifest digest.

.PP
See the 0store(1) man page for more information.

.SH LICENSE
.PP
Copyright (C) 2011 Thomas Leonard.

.PP
You may redistribute copies of this program under the terms of the GNU Lesser General Public License.
.SH BUGS
.PP
Please report bugs to the developer mailing list:

http://0install.net/support.html

.SH AUTHOR
.PP
Zero Install was created by Thomas Leonard.

.SH SEE ALSO
0install(1), 0alias(1), 0store(1)
.PP
The Zero Install web-site:

.B http://0install.net
