#!/usr/bin/env python
import os, sys
from optparse import OptionParser

__builtins__._ = lambda x: x

parser = OptionParser(usage="usage: %prog [options] interface [args]")
parser.add_option("-d", "--download-only", help="fetch but don't run", action='store_true')
parser.disable_interspersed_args()

(options, args) = parser.parse_args()

if len(args) < 1:
	parser.print_help()
	sys.exit(1)

interface_uri = args[0]
prog_args = args[1:]

import model
from gui import GUIPolicy
import gui, gtk

gtk.rc_parse_string('style "scrolled" { '
		    'GtkScrolledWindow::scrollbar-spacing = 0}\n'
		    'class "GtkScrolledWindow" style : gtk "scrolled"\n')

policy = GUIPolicy(interface_uri, prog_args,
		   download_only = bool(options.download_only))
policy.main()
