#!/usr/bin/env python
import os, sys

__builtins__._ = lambda x: x

if len(sys.argv) < 3:
	print "Usage: injector INTERFACE PROG [ARGS]"
	print "PROG is a relative path inside an implementation of INTERFACE. Eg:"
	print "injector /uri/0install/site/myprog.xml bin/myprog --help"
	sys.exit(1)
interface_uri = os.path.realpath(sys.argv[1])
prog = sys.argv[2]
prog_args = sys.argv[3:]

import model
from policy import policy
import shutil

policy.set_root_interface(interface_uri)

while policy.downloads:
	if len(policy.downloads) > 1:
		print "Need to download:"
		for p in policy.downloads:
			print "- " + p
	dl = policy.downloads.values()[0]
	print "Fetching", dl.url

	try:
		shutil.copyfileobj(file(dl.url), dl.tempfile)
	except Exception, ex:
		dl.abort(ex)
	else:
		dl.done()

import run

try:
	run.execute(prog, prog_args)
except model.SafeException, ex:
	print >>sys.stderr, ex
	if policy.network_use != network_full:
		print >>sys.stderr, "Retrying with network use = full"
		policy.network_use = model.network_full	
		policy.recalculate()
		run.execute(prog, prog_args)
