#!/usr/bin/env python
import os, sys

__builtins__._ = lambda x: x

if len(sys.argv) < 3:
	print "Usage: injector INTERFACE PROG [ARGS]"
	print "PROG is a relative path inside an implementation of INTERFACE. Eg:"
	print "injector /uri/0install/site/myprog.xml bin/myprog --help"
	sys.exit(1)
interface_uri = os.path.realpath(sys.argv[1])
prog = sys.argv[2]
prog_args = sys.argv[3:]

import model
from policy import policy

policy.set_root_interface(interface_uri)

import gui, gtk

window = gui.MainWindow(prog, prog_args)
window.show()
gtk.main()

