#!/usr/bin/env python
import os, sys

__builtins__._ = lambda x: x

if len(sys.argv) < 2:
	print "Usage: injector-gui INTERFACE [ARGS]"
	print "Eg:"
	print "injector http://example.com/myprog.xml --help"
	sys.exit(1)
interface_uri = sys.argv[1]
if not interface_uri.startswith('http:'):
	interface_uri = os.path.realpath(interface_uri)	# For testing
prog_args = sys.argv[2:]

import model
from gui import GUIPolicy
import gui, gtk

gtk.rc_parse_string('style "scrolled" { '
		    'GtkScrolledWindow::scrollbar-spacing = 0}\n'
		    'class "GtkScrolledWindow" style : gtk "scrolled"\n')

GUIPolicy(interface_uri, prog_args).main()
