#!/usr/bin/env python
import os, sys

__builtins__._ = lambda x: x

if len(sys.argv) < 2:
	print "Usage: injector INTERFACE [ARGS]"
	print "Eg:"
	print "injector http://example.com/myprog.xml --help"
	sys.exit(1)
interface_uri = sys.argv[1]
if not interface_uri.startswith('http:'):
	interface_uri = os.path.realpath(interface_uri)	# For testing
prog_args = sys.argv[2:]

import model
from policy import Policy
import download

import shutil
import sys
import gpg

class AutoPolicy(Policy):
	monitored_downloads = None

	def __init__(self, interface_uri):
		Policy.__init__(self, interface_uri)
		self.monitored_downloads = []

	def monitor_download(self, dl):
		error_stream = dl.start()
		self.monitored_downloads.append((error_stream, dl))

	def start_downloading_impls(self):
		for iface, impl in self.get_uncached_implementations():
			if not impl.download_sources:
				raise SafeException("Implementation " + impl + " of "
					"interface " + iface + " cannot be "
					"downloaded (no download locations given in "
					"interface!")
			dl = download.begin_impl_download(impl.download_sources[0])
			self.monitor_download(dl)

# Singleton instance used everywhere...
policy = AutoPolicy(interface_uri)
policy.recalculate()

def wait_for_downloads():
	while policy.monitored_downloads:
		print "Currently downloading:"
		for e, dl in policy.monitored_downloads:
			print "- " + dl.url

		for e, dl in policy.monitored_downloads[:]:
			errors =  e.read()
			if errors:
				print "Got errors:", errors
			e.close()
			policy.monitored_downloads.remove((e, dl))
			data = dl.error_stream_closed()
			if isinstance(dl, download.InterfaceDownload):
				policy.check_signed_data(dl, data)
			elif isinstance(dl, download.ImplementationDownload):
				policy.add_to_cache(dl.source, data)
			else:
				raise Exception("Unknown download type %s" % dl)

import run

def execute():
	policy.start_downloading_impls()

	wait_for_downloads()
		
	run.execute(policy, prog_args)

# Get interfaces...
wait_for_downloads()

try:
	execute()
except model.SafeException, ex:
	if policy.network_use != model.network_full:
		print >>sys.stderr, "Error. Retrying with network use = full"
		policy.network_use = model.network_full	
		policy.recalculate()
		try:
			execute()
		except model.SafeException, ex:
			print >>sys.stderr, ex
	else:
		print >>sys.stderr, ex
