#!/usr/bin/env python
import zeroinstall, sys, os, shutil

os.system('svn status')

name = 'injector-' + zeroinstall.version
a = raw_input("Release " + name + "? [y/N]")
if not a or a not in 'Yy':
	sys.exit(0)

if os.system('cd tests && ./testall.py'):
	print "ERROR: Unit test failure. Stop"
	sys.exit(1)

if os.system('svn ls file:///home/svn/releases/' + name + ' >/dev/null') == 0:
	print "WARNING: releases/" + name + " already exists"
	a = raw_input("Overwrite " + name + "? [y/N]")
	if not a or a not in 'Yy':
		sys.exit(0)
	os.system('svn rm file:///home/svn/releases/' + name + ' -m overwrite')

if os.system('svn cp -m "Released ' + name + '" ' +
	  'file:///home/svn/injector/injector '
	  'file:///home/svn/releases/' + name):
	print "Failed to make release"
	sys.exit(1)

if os.path.isdir(name):
	shutil.rmtree(name)
os.system('svn export file:///home/svn/releases/' + name + ' ' + name)
os.chdir(name)
os.system('python setup.py sdist')
os.system('dpkg-buildpackage -rfakeroot')

os.system('svn up')
