#!/usr/bin/env python
import zeroinstall, sys, os

os.system('svn status')

name = 'injector-' + zeroinstall.version
a = raw_input("Release " + name + "? [y/N]")
if not a or a not in 'Yy':
	sys.exit(0)

if os.system('svn cp -m "Released ' + name + '" ' +
	  'file:///home/svn/injector/injector '
	  'file:///home/svn/releases/' + name):
	print "Try svn rm file:///home/svn/releases/" + name
	sys.exit(1)

os.system('svn export file:///home/svn/releases/' + name + ' ' + name)
os.chdir(name)
os.system('python setup.py sdist')
