#!/usr/bin/env python
import os, sys

__builtins__._ = lambda x: x

if len(sys.argv) < 3:
	print "Usage: injector INTERFACE PROG [ARGS]"
	print "PROG is a relative path inside an implementation of INTERFACE. Eg:"
	print "injector /uri/0install/site/myprog.xml bin/myprog --help"
	sys.exit(1)
interface_uri = sys.argv[1]
prog = sys.argv[2]
prog_args = sys.argv[3:]

import model
from policy import policy

interface = model.get_interface(interface_uri)
policy.set_root_iterface(interface)
policy.recalculate()

import run

try:
	run.execute(interface, prog, prog_args)
except model.SafeException, ex:
	print >>sys.stderr, ex

	import reader
	for i in policy.walk_interfaces():
		print "Updating", i
		reader.update_from_network(i)
	policy.recalculate()

	run.execute(interface, prog, prog_args)
