"""Adding icons and menu items using the freedesktop.org system.
(xdg = X Desktop Group)
"""
# Copyright (C) 2009, Thomas Leonard
# See the README file for details, or visit http://0install.net.

from zeroinstall import _, logger
import shutil, os, tempfile

from zeroinstall import SafeException
from zeroinstall.support import basedir

_template = """[Desktop Entry]
# This file was generated by 0install.
# See the Zero Install project for details: http://0install.net
Type=Application
Version=1.0
Name=%(name)s
Comment=%(comment)s
Exec=%(0launch)s -- %(iface)s %%f
Categories=Application;%(category)s
"""

_icon_template = """Icon=%s
"""

def add_to_menu(feed, icon_path, category, zlaunch=None):
	"""Write a .desktop file for this application.
	@param feed: the master feed of the program being added
	@param icon_path: the path of the icon, or None
	@param category: the freedesktop.org menu category"""
	iface_uri = feed['url']

	tmpdir = tempfile.mkdtemp(prefix = 'zero2desktop-')
	try:
		desktop_name = os.path.join(tmpdir, 'zeroinstall-%s.desktop' % feed['name'].lower().replace(os.sep, '-').replace(' ', ''))
		desktop = open(desktop_name, 'w')
		desktop.write(_template % {'name': feed['name'],
                                   'comment': feed['summary'],
                                   '0launch': zlaunch or '0launch',
                                   'iface': iface_uri,
                                   'category': category})
		if icon_path:
			desktop.write(_icon_template % icon_path)
		if feed['needs-terminal']:
			desktop.write('Terminal=true\n')
		desktop.close()
		status = os.spawnlp(os.P_WAIT, 'xdg-desktop-menu', 'xdg-desktop-menu', 'install', desktop_name)
	finally:
		shutil.rmtree(tmpdir)

	if status:
		raise SafeException(_('Failed to run xdg-desktop-menu (error code %d)') % status)
