#!/bin/sh
if [ "$4" = "python-bittorrent" ]; then
	echo "3.4.2-10ubuntu2	any	install ok installed"
elif [ "$4" = "libxcomposite-dev" ]; then
	echo "1:0.3.1-1	i386	install ok installed"
elif [ "$4" = "openjdk-7-jre" ]; then
	echo "7~u3-2.1.1-3	amd64	install ok installed"
else
	exit 1
fi
