#!/bin/sh
if [ "$1 $2" == "echo installed" ]; then
cat << EOF
zeroinstall-injector           @0.54_0 
EOF
elif [ "$1 $2" == "-v installed" ]; then
cat << EOF
The following ports are currently installed:
  zeroinstall-injector @0.54_0
  zeroinstall-injector @1.0_0 (active) platform='darwin 10' archs='noarch'
EOF
fi
